import { expect } from '@esm-bundle/chai';

import { parseCEM } from './parse.js';

describe('parse', () => {
  describe('parseCEM', () => {
    it('fails on missing schema version', () => {
      const parse = () => parseCEM({});
      expect(parse).to.throw('No schema version found in manifest data. Was it generated by a CEM compliant tool?');
    });

    it('fails on outdated schema versions', () => {
      const parse = () => parseCEM({ schemaVersion: '0.0.10' });
      expect(parse).to.throw('No parser for CEM version 0.0.10 found.');
    });

    it('parses the manifest', async () => {
      const response = await fetch('/fixtures/manifests/wcp-client.json');
      const clientManifest = await response.json();
      const data = parseCEM(clientManifest);

      expect(data).to.have.property('elements');
    });
  });
});
