/* eslint-disable @typescript-eslint/no-explicit-any */
import { expect } from '@esm-bundle/chai';

import { parseCEM } from './parse.js';

describe('parse', () => {
  describe('parseCEM', () => {
    it('fails on missing schema version', () => {
      const parse = () => parseCEM({});
      expect(parse).to.throw('No schema version found in manifest data. Was it generated by a CEM compliant tool?');
    });

    it('fails on outdated schema versions', () => {
      const parse = () => parseCEM({ schemaVersion: '0.0.10' });
      expect(parse).to.throw('No parser for CEM version 0.0.10 found.');
    });

    it.each`
      name        | lib
      ${'SAB UI'} | ${'sab-ui'}
      ${'WCP'}    | ${'wcp-client'}
      ${'ZUi'}    | ${'zui'}
    `('parses the $name manifest', async ({ lib }: any) => {
      const { default: raw } = await import(`../../../fixtures/manifests/${lib}.json`, { assert: { type: 'json' } });
      const data = parseCEM(raw);

      expect(data).to.have.property('elements');
    });
  });
});
