name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  clean:
    name: Clean up orphaned deployments
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Remove PRs
        run: |
          pr_ids=$(gh api --header 'Accept: application/vnd.github+json' --method GET /repos/${{ github.repository }}/pulls | jq -r '. | map(.number) | join("\\|")')
          find pr -type d -mindepth 1 -maxdepth 1 ! -regex "^pr\/\(${pr_ids}\)" -exec rm -rf {}
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Remove releases
        run: |
          released_versions=$(gh api --header 'Accept: application/vnd.github+json' --method GET /repos/${{ github.repository }}/releases | jq -r '. + [{"tag_name": "latest"}, {"tag_name": "pr"}] | map(.tag_name | sub("\\.";"\\.";"g")) | join("\\|")')
          find . -not -path '*/.*' -type d -mindepth 1 -maxdepth 1 -not -regex "^\.\/\(${released_versions}\)" -exec rm -rf {}
        env:
          GH_TOKEN: ${{ github.token }}

  deploy:
    name: Deploy
    needs: clean
    runs-on: ubuntu-latest
    environment:
      name: Pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
