name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: "."
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
